// Daily report email generation

import { EmailMessage } from 'cloudflare:email';
import { createMimeMessage } from 'mimetext';

export function generateReportHtml(date, snapshots, spyDailyPct) {
  // Sort by daily P&L descending
  const sorted = [...snapshots].sort((a, b) => b.daily_pnl - a.daily_pnl);
  const top3 = sorted.slice(0, 3);
  const bottom3 = sorted.slice(-3).reverse();

  const totalValue = snapshots.reduce((s, snap) => s + snap.portfolio_value, 0);
  const totalDailyPnl = snapshots.reduce((s, snap) => s + snap.daily_pnl, 0);
  const totalCumPnl = snapshots.reduce((s, snap) => s + snap.cumulative_pnl, 0);
  const totalAllocation = snapshots.length * 3000;

  const pausedAgents = snapshots.filter(s => s.max_drawdown > 0.10);

  return `<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
  .container { max-width: 800px; margin: 0 auto; background: white; border-radius: 8px; padding: 24px; }
  h1 { color: #1a1a1a; font-size: 22px; margin-bottom: 4px; }
  h2 { color: #333; font-size: 16px; margin-top: 24px; border-bottom: 1px solid #eee; padding-bottom: 8px; }
  .date { color: #666; font-size: 14px; margin-bottom: 20px; }
  .summary { display: flex; gap: 16px; flex-wrap: wrap; margin-bottom: 20px; }
  .stat { background: #f8f9fa; border-radius: 6px; padding: 12px 16px; flex: 1; min-width: 150px; }
  .stat-label { font-size: 11px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
  .stat-value { font-size: 20px; font-weight: 600; margin-top: 4px; }
  .positive { color: #16a34a; }
  .negative { color: #dc2626; }
  .neutral { color: #666; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { background: #f8f9fa; text-align: left; padding: 8px 12px; font-weight: 600; color: #444; }
  td { padding: 8px 12px; border-bottom: 1px solid #f0f0f0; }
  .highlight-row { background: #fffbeb; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 11px; font-weight: 500; }
  .badge-green { background: #dcfce7; color: #166534; }
  .badge-red { background: #fef2f2; color: #991b1b; }
  .footer { margin-top: 24px; padding-top: 16px; border-top: 1px solid #eee; font-size: 12px; color: #999; }
</style>
</head>
<body>
<div class="container">
  <h1>Stocktrade Daily Report</h1>
  <div class="date">${date} | SPY: ${formatPct(spyDailyPct)}</div>

  <div class="summary">
    <div class="stat">
      <div class="stat-label">Total Portfolio</div>
      <div class="stat-value">${formatMoney(totalValue)}</div>
    </div>
    <div class="stat">
      <div class="stat-label">Daily P&L</div>
      <div class="stat-value ${totalDailyPnl >= 0 ? 'positive' : 'negative'}">${formatMoney(totalDailyPnl)} (${formatPct(totalDailyPnl / totalAllocation)})</div>
    </div>
    <div class="stat">
      <div class="stat-label">Cumulative P&L</div>
      <div class="stat-value ${totalCumPnl >= 0 ? 'positive' : 'negative'}">${formatMoney(totalCumPnl)} (${formatPct(totalCumPnl / totalAllocation)})</div>
    </div>
    <div class="stat">
      <div class="stat-label">Active Agents</div>
      <div class="stat-value">${snapshots.length - pausedAgents.length} / ${snapshots.length}</div>
    </div>
  </div>

  <h2>Top Performers</h2>
  ${agentTable(top3)}

  <h2>Bottom Performers</h2>
  ${agentTable(bottom3)}

  <h2>All Agents</h2>
  ${agentTable(sorted)}

  ${pausedAgents.length > 0 ? `
  <h2>Paused Agents</h2>
  <p style="color: #dc2626; font-size: 13px;">The following agents exceeded 10% drawdown and have been paused:</p>
  <ul style="font-size: 13px;">
    ${pausedAgents.map(a => `<li>${a.agent_id} — drawdown ${formatPct(a.max_drawdown)}</li>`).join('')}
  </ul>
  ` : ''}

  <div class="footer">
    Generated by Stocktrade on Cloudflare Workers | Paper trading via Alpaca Markets
  </div>
</div>
</body>
</html>`;
}

function agentTable(agents) {
  return `<table>
  <tr>
    <th>Agent</th>
    <th>Daily P&L</th>
    <th>Cumulative</th>
    <th>Positions</th>
    <th>Win Rate</th>
    <th>Sharpe</th>
    <th>Alpha</th>
  </tr>
  ${agents.map(a => `<tr>
    <td><strong>${a.agent_id}</strong></td>
    <td class="${a.daily_pnl >= 0 ? 'positive' : 'negative'}">${formatMoney(a.daily_pnl)} (${formatPct(a.daily_pnl_pct)})</td>
    <td class="${a.cumulative_pnl >= 0 ? 'positive' : 'negative'}">${formatMoney(a.cumulative_pnl)} (${formatPct(a.cumulative_pnl_pct)})</td>
    <td>${a.open_positions}</td>
    <td>${a.win_rate != null ? formatPct(a.win_rate) : '—'}</td>
    <td>${a.sharpe_ratio != null ? a.sharpe_ratio.toFixed(2) : '—'}</td>
    <td class="${(a.alpha || 0) >= 0 ? 'positive' : 'negative'}">${a.alpha != null ? formatPct(a.alpha) : '—'}</td>
  </tr>`).join('')}
  </table>`;
}

function formatMoney(amount) {
  const sign = amount >= 0 ? '' : '-';
  return `${sign}$${Math.abs(amount).toFixed(2)}`;
}

function formatPct(pct) {
  if (pct == null) return '—';
  const sign = pct >= 0 ? '+' : '';
  return `${sign}${(pct * 100).toFixed(2)}%`;
}

export async function sendDailyReport(env, date, snapshots, spyDailyPct) {
  const html = generateReportHtml(date, snapshots, spyDailyPct);
  const totalDailyPnl = snapshots.reduce((s, snap) => s + snap.daily_pnl, 0);
  const pnlStr = totalDailyPnl >= 0 ? `+$${totalDailyPnl.toFixed(2)}` : `-$${Math.abs(totalDailyPnl).toFixed(2)}`;

  // Store report in R2 for archive
  await env.REPORTS.put(
    `reports/${date}.html`,
    html,
    { httpMetadata: { contentType: 'text/html' } }
  );

  // Send email via Email Workers send_email binding
  try {
    const msg = createMimeMessage();
    msg.setSender({ name: 'Stocktrade', addr: 'stocktrade@thebackend.dev' });
    msg.setRecipient('michael.zemel@gmail.com');
    msg.setSubject(`Stocktrade ${date}: ${pnlStr}`);
    msg.addMessage({ contentType: 'text/html', data: html });

    const message = new EmailMessage(
      'stocktrade@thebackend.dev',
      'michael.zemel@gmail.com',
      msg.asRaw()
    );
    await env.EMAIL.send(message);
    return { sent: true };
  } catch (e) {
    console.error(`Email send failed: ${e.message}`);
    // Report is still in R2 even if email fails
    return { sent: false, error: e.message };
  }
}
